language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
- npm install -g bower
- bower install
before_deploy: 'grunt dist'
deploy:
  provider: s3
  access_key_id: AKIAI57JEIKDVDYUON6Q
  secret_access_key:
    secure: C5+G5sJo7qBAPRL5/F4+g45BA8J/WskBX3MxfWSyRmKB2Sz45VaZJ9/DaRtEdVp0hqvy34iy2OFhAlHGlofHnTElc/p3KIxSZX/8EqJzWLgDO25hp7fEEiIVl+IYx2bW3LZj4tqLoLv5aQart8l7b0G+ARPbbixrM+CXiI7rOME=
  bucket: aosgroup-production
  region: eu-west-1
  local-dir: dist
  skip_cleanup: true
  on:
    repo: timstott/aosgroup.kz
